services:
  - type: cron
    name: cgv-imax-alert
    env: docker
    schedule: "* * * * *"  # 1분마다 실행
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GITHUB_ACTIONS
        value: "true"



