services:
  - type: web
    name: cgv-imax-alert
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GITHUB_ACTIONS
        value: "true"



